// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TatumPlatform.MyConsole.Model;

#nullable disable

namespace TatumPlatform.MyConsole.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20211122105326_Add-BlockchainTransaction")]
    partial class AddBlockchainTransaction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TatumPlatform.MyConsole.Model.BlockchainTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<int?>("NetworkId")
                        .HasColumnType("int");

                    b.Property<long?>("ParentBlockchainTransactionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentBlockchainTransactionId")
                        .IsUnique()
                        .HasFilter("[ParentBlockchainTransactionId] IS NOT NULL");

                    b.ToTable("BlockchainTransaction");
                });

            modelBuilder.Entity("TatumPlatform.MyConsole.Model.MyTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyTest");
                });

            modelBuilder.Entity("TatumPlatform.MyConsole.Model.BlockchainTransaction", b =>
                {
                    b.HasOne("TatumPlatform.MyConsole.Model.BlockchainTransaction", "ChildBlockchainTransaction")
                        .WithOne("ParentBlockchainTransaction")
                        .HasForeignKey("TatumPlatform.MyConsole.Model.BlockchainTransaction", "ParentBlockchainTransactionId");

                    b.Navigation("ChildBlockchainTransaction");
                });

            modelBuilder.Entity("TatumPlatform.MyConsole.Model.BlockchainTransaction", b =>
                {
                    b.Navigation("ParentBlockchainTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
